### ISSUE TITLE
Configuração e geração do pre-textual

### ISSUE THREAD

**Issue by edusantana** [abntex/trabalho-academico-pandoc-abntex2#7]
- [x] Folha de rosto (obrigatório)
- [x] Errata (opcional)
- [x] Folha de aprovação (obrigatório)
- [x] Dedicatória (opcional) #11
- [x] Agradecimentos (opcional) #12 
- [x] Epígrafe (opcional) #13
- [x] Resumos (obrigatório) #14
- [x] Lista de ilustrações (opcional) #15
- [x] Lista de tabelas (opcional) #16
- [x] Lista de abreviaturas e siglas (opcional) #17
- [x] Lista de símbolos (opcional) #18
- [x] Sumário (obrigatório) #19
